version: "2"
run:
  build-tags:
    - lint
  issues-exit-code: 1
linters:
  disable:
    - gocyclo
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - contrib/
      - misc/
