#!/bin/sh

set -ef

PKGSRC=${PKGSRC:-github.com/yggdrasil-network/yggdrasil-go/src/version}
PKGNAME=${PKGNAME:-$(sh contrib/semver/name.sh)}
PKGVER=${PKGVER:-$(sh contrib/semver/version.sh --bare)}

LDFLAGS="-X $PKGSRC.buildName=$PKGNAME -X $PKGSRC.buildVersion=$PKGVER"
ARGS="-v"

while getopts "utc:l:dro:p" option
do
  case "$option"
  in
  u) UPX=true;;
  t) TABLES=true;;
  c) GCFLAGS="$GCFLAGS $OPTARG";;
  l) LDFLAGS="$LDFLAGS $OPTARG";;
  d) ARGS="$ARGS -tags debug" DEBUG=true;;
  r) ARGS="$ARGS -race";;
  o) ARGS="$ARGS -o $OPTARG";;
  p) ARGS="$ARGS -buildmode=pie";;
  esac
done

if [ -z $TABLES ] && [ -z $DEBUG ]; then
  LDFLAGS="$LDFLAGS -s -w"
fi

if [[ "$CGO_ENABLED" == "1" ]]; then
  LIBNAME="ygglibrary"
  if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    LIBNAME="$LIBNAME.so"
    echo "Building: $LIBNAME"
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    LIBNAME="$LIBNAME.dylib"
    echo "Building: $LIBNAME"
  elif [[ "$OSTYPE" == "win32" ]]; then
    LIBNAME="$LIBNAME.dll"
    echo "Building: $LIBNAME"
  fi
  go build -ldflags="$LDFLAGS" -buildmode=c-shared -o="$LIBNAME" ./export
fi

for CMD in yggdrasil yggdrasilctl ; do
  echo "Building: $CMD"
  go build $ARGS -ldflags="$LDFLAGS" -gcflags="$GCFLAGS" ./cmd/$CMD

  if [ $UPX ]; then
    upx --brute $CMD
  fi
done
