#! /bin/sh
# postrm script for mesh
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
# for details, see /usr/share/doc/packaging-manual/

case "$1" in
    purge)
       rm -rf /apps/mesh
       systemctl restart apache2.service                                                                                                                                   
       event_push app meshd '<delete-s resource-type="LocalApp" resource-id="LocalApp"><LocalApp appname="mesh" success="1" reboot="0"/></delete-s>' 0 0
       ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
       ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0

esac
